# Generated by Django 4.2.6 on 2023-10-08 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='slug',
            field=models.SlugField(null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
