# Generated by Django 4.2.6 on 2023-10-18 15:34

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0004_rename_clients_address_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='country',
            field=django_countries.fields.CountryField(max_length=2),
        ),
        migrations.AlterField(
            model_name='clients',
            name='birthdate',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='email',
            field=models.EmailField(max_length=255),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.PositiveBigIntegerField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='expiration_date',
            field=models.DateField(max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='number',
            field=models.PositiveBigIntegerField(),
        ),
    ]
