# Generated by Django 4.2.6 on 2023-10-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0006_address_zipcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='document',
            name='name',
        ),
        migrations.AlterField(
            model_name='clients',
            name='addressC',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.address'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='contactC',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.contact'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='documentC',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.document'),
        ),
    ]
