# Generated by Django 4.2.6 on 2023-10-25 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0007_remove_address_name_remove_contact_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('lastname', models.CharField(max_length=255)),
                ('age_group', models.CharField(max_length=255)),
            ],
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='addressC',
            new_name='client_address',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='contactC',
            new_name='client_contact',
        ),
        migrations.RenameField(
            model_name='clients',
            old_name='documentC',
            new_name='client_document',
        ),
        migrations.RemoveField(
            model_name='clients',
            name='reservations',
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(null=True)),
                ('hotel', models.CharField(max_length=255)),
                ('checkin_date', models.DateField(max_length=255)),
                ('checkout_date', models.DateField(max_length=255)),
                ('price', models.PositiveBigIntegerField()),
                ('room', models.CharField(max_length=255)),
                ('active_status', models.CharField(max_length=255)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.clients')),
                ('guestsR', models.ManyToManyField(blank=True, related_name='reservations', to='nonius_travel.guests')),
            ],
        ),
        migrations.AddField(
            model_name='guests',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.reservations'),
        ),
        migrations.AddField(
            model_name='clients',
            name='client_reservation',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.reservations'),
        ),
    ]
