# Generated by Django 4.2.6 on 2023-10-25 21:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0008_guests_rename_addressc_clients_client_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservations',
            old_name='guestsR',
            new_name='reservation_guests',
        ),
        migrations.AlterField(
            model_name='guests',
            name='reservation',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.reservations'),
        ),
    ]
