# Generated by Django 4.2.6 on 2023-10-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0010_address_created_at_clients_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guests',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
