# Generated by Django 4.2.6 on 2023-10-28 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0011_guests_slug'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clients',
            options={'ordering': ['created_at']},
        ),
    ]
