# Generated by Django 4.2.6 on 2023-10-28 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0013_alter_address_client_alter_contact_client_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.clients'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.clients'),
        ),
        migrations.AlterField(
            model_name='document',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.clients'),
        ),
        migrations.AlterField(
            model_name='guests',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.reservations'),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.clients'),
        ),
    ]
