# Generated by Django 4.2.6 on 2023-10-28 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0015_alter_clients_client_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='client_address',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.address'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_contact',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.contact'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_document',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.document'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='client_reservation',
            field=models.ManyToManyField(blank=True, related_name='clients', to='nonius_travel.reservations'),
        ),
    ]
