# Generated by Django 4.2.6 on 2023-10-28 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0016_alter_clients_client_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=255)),
                ('expiration_date', models.DateField(max_length=255)),
                ('vendor', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='hotel',
            new_name='confirmation_id',
        ),
        migrations.RenameField(
            model_name='reservations',
            old_name='room',
            new_name='policies',
        ),
        migrations.RemoveField(
            model_name='address',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='document',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='guests',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='reservations',
            name='slug',
        ),
        migrations.AddField(
            model_name='reservations',
            name='room_type',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='address',
            name='zipcode',
            field=models.CharField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reservations',
            name='price',
            field=models.CharField(max_length=255),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('method', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('card', models.ManyToManyField(blank=True, related_name='payments', to='nonius_travel.card')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.reservations')),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='reservation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nonius_travel.reservations'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='payment_information',
            field=models.ManyToManyField(blank=True, related_name='reservations', to='nonius_travel.payment'),
        ),
    ]
