# Generated by Django 4.2.6 on 2023-10-28 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0019_alter_address_slug_alter_card_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='card',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='clients',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='contact',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='guests',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='payment',
            name='slug',
            field=models.SlugField(),
        ),
        migrations.AlterField(
            model_name='reservations',
            name='slug',
            field=models.SlugField(),
        ),
    ]
