# Generated by Django 4.2.6 on 2023-10-31 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nonius_travel', '0020_alter_address_slug_alter_card_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservations',
            name='checkin_time',
            field=models.TimeField(default='00:00:00'),
        ),
        migrations.AddField(
            model_name='reservations',
            name='checkout_time',
            field=models.TimeField(default='00:00:00'),
        ),
    ]
